# Generated by Django 4.2 on 2025-11-15 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZendeskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID)', primary_key=True, serialize=False)),
                ('employee_id', models.CharField(help_text="Agent's company ID number", max_length=20)),
                ('role', models.CharField(blank=True, default='Agent', max_length=100, null=True)),
                ('country', models.CharField(blank=True, help_text='Agent market', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='Associated Django user account', on_delete=django.db.models.deletion.CASCADE, related_name='zendesk_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zendesk Agent',
                'verbose_name_plural': 'Zendesk Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='zendeskprofile',
            index=models.Index(fields=['employee_id'], name='zendesk_age_employe_4172e9_idx'),
        ),
        migrations.AddIndex(
            model_name='zendeskprofile',
            index=models.Index(fields=['user'], name='zendesk_age_user_id_3a0494_idx'),
        ),
    ]
